
# PATHS
DIRECTORY = "/Users/andreavitullo/Desktop/DATABASE_TEST"

# FORMATS
FILE_FORMAT = "wav"
START_FORMAT = "AUDIO.wav"
FINAL_FORMAT = "Final.wav"
SPLIT_FORMAT = "_SPLIT.wav"

# MFCC AND NN PARAMETERS
N_MFCC = 20
N_FRAMES = 200
NUM_CLASSES = 1
EPOCHS = 5

# SEQUENCE LENGTH of the sliding window for LSTM.
SEQ_LEN = 100  # 3.2 seconds

# PARAMETERS FOR SPECTRAL AUGMENTATION
SPECAUG_FREQ_MASK_PROB = 0.3
SPECAUG_TIME_MASK_PROB = 0.3
SPECAUG_FREQ_MASK_MAX_WIDTH = N_MFCC // 5
SPECAUG_TIME_MASK_MAX_WIDTH = SEQ_LEN // 5
